# Ask to lookup a known frame in the tf tree. "moving_to_task_frame" is ignored in this case
byte LOOKUP=0

# Provide a transform to the moving frame. "moving_frame_name" is ignored in this case
# "moving_to_task_frame" is the transform from the moving frame (e.g. gripper) to the task frame (where the screw is defined)
byte PROVIDED=1

# Source of moving frame
byte moving_frame_source

# Moving frame input
string moving_frame_name
geometry_msgs/TransformStamped moving_to_task_frame

# Screw axis to move about
affordance_primitive_msgs/ScrewStamped screw

# Task Impedance
affordance_primitive_msgs/CartesianFloat task_impedance

# Velocity to move along the screw
float64 theta_dot
---
# Resulting velocity of the moving frame
geometry_msgs/TwistStamped moving_frame_twist

# Estimate of screw theta we moved since the last check
float64 delta_theta_last_timestep

# Wrench required in the EE frame (TODO: make this in the F/T frame)
geometry_msgs/WrenchStamped expected_wrench
